#Inicialização dos Dados

Abrir os dados dos arquivos e formata-los para o processamento dos dados.

###Import's

Importar as bibliotecas que serão utilizadas.


In [16]:
from scipy.io import loadmat                # Biblioteca para carregar arquivos .mat
import numpy as np                          # Biblioteca do numpy para manipulação de matrizes

###Carregamento

Carregar as bases de dados.

In [17]:
# Ativa/destiva o uso do Google Drive

if False:
    from google.colab import drive
    drive.mount('/content/drive')
    path = 'drive/MyDrive/'
else:
    path = ''

In [18]:
avi_data = list()                               # Lista para armazenar os dados dos arquivos .mat

for i in range(1,6):
    avi_data.append(loadmat(f"{path}datasets/avi/multi/Sub{i}_1_multitarget.mat"))

###Extração

Extração dos dados

In [19]:
X = [d['Data'][0][0][7] for d in avi_data]              # Lista com os dados dos participantes
Y = [d['Data'][0][0][8][0] for d in avi_data]           # Lista com os rótulos (sequências) dos participantes


print("Divisão dos dados:")
for data in X:
    print(data.shape, data.T.shape)

print("\nDivisão dos rótulos (sequências):")
for data in Y:
    print(data)

Divisão dos dados:
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]


###Padronização

Os dados de cada participante já estão padronizados.

###Salvar Dados

Salvar os dados padronizados de cada participante em estrutura do numpy em arquivos separados.

In [20]:
# Salvando os dados e rótulos padronizados em arquivos .npy

for i in range (5):
  np.save(f"{path}datasets/avi/multi/data_sub{i+1}.npy", X[i])
  np.save(f"{path}datasets/avi/multi/labels_sub{i+1}.npy", Y[i])
