#Inicialização dos Dados

Abrir os dados dos arquivos e formata-los para o processamento dos dados.

###Import's

Importar as bibliotecas que serão utilizadas.


In [1]:
from scipy.io import loadmat
import numpy as np

###Carregamento

Carregar as bases de dados.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
avi_data = list()
for i in range(1,6):
    avi_data.append(loadmat(f"drive/MyDrive/datasets/avi/multi/Sub{i}_1_multitarget.mat"))

###Extração

Extração dos dados

In [17]:
X = [d['Data'][0][0][7] for d in avi_data]
Y = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape, data.T.shape)

print("\nDivisão dos rótulos (sequências):")
for data in Y:
    print(data)

Divisão dos dados:
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]


###Padronização

Os dados de cada participante já estão padronizados.

###Salvar Dados

Salvar os dados padronizados de cada participante em estrutura do numpy em arquivos separados.

In [19]:
tempX = list()
# y = Y[0]




for i in range (5):
  # tempX.append(X[i])
  np.save(f"drive/MyDrive/datasets/avi/multi/data_sub{i+1}.npy", X[i])
  np.save(f"drive/MyDrive/datasets/avi/multi/labels_sub{i+1}.npy", Y[i])

# X = np.array(tempX)
# X.shape



(5, 8192, 10)