#Inicialização dos Dados

Abrir os dados dos arquivos e formata-los para o processamento dos dados.

###Import's

Importar as bibliotecas que serão utilizadas.


In [3]:
from scipy.io import loadmat
import numpy as np

###Carregamento

Carregar as bases de dados.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
avi_data = list()
for i in range(1,6):
    avi_data.append(loadmat(f"drive/MyDrive/datasets/avi/multi/Sub{i}_1_multitarget.mat"))

###Extração

Extração dos dados

In [5]:
X = [d['Data'][0][0][7] for d in avi_data]
y = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape, data.T.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]


In [10]:
# padronizando 1º participante

temp = list()
temp.append(X[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))])
temp.append(X[2])
temp.append(X[3])

y = y[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))]
X = np.array(temp)
X.shape

<ipython-input-10-634712278921>:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X = np.array(temp)


ValueError: ignored